/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppSelectedEvent } from "./components/singul/singul.helpers";
export { AppSelectedEvent } from "./components/singul/singul.helpers";
export namespace Components {
    interface SingulJs {
        "auth": string;
        /**
          * @default ''
         */
        "class": string;
        /**
          * @default {}
         */
        "customStyles": string | { [key: string]: any };
        "placeholder": string;
        "testingProp": string;
    }
}
export interface SingulJsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSingulJsElement;
}
declare global {
    interface HTMLSingulJsElementEventMap {
        "appSelected": AppSelectedEvent;
    }
    interface HTMLSingulJsElement extends Components.SingulJs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSingulJsElementEventMap>(type: K, listener: (this: HTMLSingulJsElement, ev: SingulJsCustomEvent<HTMLSingulJsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSingulJsElementEventMap>(type: K, listener: (this: HTMLSingulJsElement, ev: SingulJsCustomEvent<HTMLSingulJsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSingulJsElement: {
        prototype: HTMLSingulJsElement;
        new (): HTMLSingulJsElement;
    };
    interface HTMLElementTagNameMap {
        "singul-js": HTMLSingulJsElement;
    }
}
declare namespace LocalJSX {
    interface SingulJs {
        "auth": string;
        /**
          * @default ''
         */
        "class"?: string;
        /**
          * @default {}
         */
        "customStyles"?: string | { [key: string]: any };
        "onAppSelected"?: (event: SingulJsCustomEvent<AppSelectedEvent>) => void;
        "placeholder"?: string;
        "testingProp"?: string;
    }
    interface IntrinsicElements {
        "singul-js": SingulJs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "singul-js": LocalJSX.SingulJs & JSXBase.HTMLAttributes<HTMLSingulJsElement>;
        }
    }
}
