/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppSelectedEvent } from "./components/app-search-bar/app-search-bar";
export { AppSelectedEvent } from "./components/app-search-bar/app-search-bar";
export namespace Components {
    interface AppSearchBar {
        /**
          * Auth token for the URL
         */
        "auth": string;
        /**
          * Custom CSS class for styling
          * @default ''
         */
        "class": string;
        /**
          * Custom styles object for complete customization
          * @default {}
         */
        "customStyles": string | { [key: string]: any };
        /**
          * Placeholder text for the search input
          * @default 'Search apps...'
         */
        "placeholder": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface AppSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppSearchBarElement;
}
declare global {
    interface HTMLAppSearchBarElementEventMap {
        "appSelected": AppSelectedEvent;
    }
    interface HTMLAppSearchBarElement extends Components.AppSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppSearchBarElementEventMap>(type: K, listener: (this: HTMLAppSearchBarElement, ev: AppSearchBarCustomEvent<HTMLAppSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppSearchBarElementEventMap>(type: K, listener: (this: HTMLAppSearchBarElement, ev: AppSearchBarCustomEvent<HTMLAppSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppSearchBarElement: {
        prototype: HTMLAppSearchBarElement;
        new (): HTMLAppSearchBarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-search-bar": HTMLAppSearchBarElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppSearchBar {
        /**
          * Auth token for the URL
         */
        "auth": string;
        /**
          * Custom CSS class for styling
          * @default ''
         */
        "class"?: string;
        /**
          * Custom styles object for complete customization
          * @default {}
         */
        "customStyles"?: string | { [key: string]: any };
        /**
          * Emitted when an app is selected
         */
        "onAppSelected"?: (event: AppSearchBarCustomEvent<AppSelectedEvent>) => void;
        /**
          * Placeholder text for the search input
          * @default 'Search apps...'
         */
        "placeholder"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "app-search-bar": AppSearchBar;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-search-bar": LocalJSX.AppSearchBar & JSXBase.HTMLAttributes<HTMLAppSearchBarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
